FROM golang:1.18.4-alpine AS builder

RUN apk add --no-cache git

ARG BUILD=0.0.0-development

WORKDIR /github.com/danstis/go-read-burn/
COPY ../go.mod .
COPY ../go.sum .
RUN go mod download
COPY . .
RUN mkdir /app
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags "-s -w -X 'github.com/danstis/go-read-burn/internal/version.Version=$BUILD'" -o /app/go-read-burn ./cmd/go-read-burn

FROM alpine:3
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /app/* ./
COPY --from=builder /usr/local/go/lib/time/zoneinfo.zip /
ENV TZ=Australia/Brisbane \
    ZONEINFO=/zoneinfo.zip
CMD [ "./go-read-burn" ]
