# docker-compose up -d --build --remove-orphans
# or with new docker compose 2.x
# docker compose up -d --build --remove-orphans
version: '3'
name: go-read-burn
services:
  app:
    build:
      context: ../
      dockerfile: cmd/go-read-burn/dockerfile
      args:
        - COMMIT=${COMMIT}
        - DATE=${DATE}
        - VERSION=${VERSION}
    restart: "no" #on-failure
    environment:
      - "GRB_DB_PATH=/data/secrets.db"
    ports:
      - "8080:80"
    volumes:
      - "../db:/data"
